### ISSUE TITLE
Error "There is already an open DataReader associated with this Command which must be closed first"

### ISSUE THREAD

**Issue by riverstore** [smartstoreag/SmartStoreNET#687] opened 2015-05-03 16:24 UTC
Hi! On access to http://localhost:49381/Admin/SpecificationAttribute/List I got this error message

"There is already an open DataReader associated with this Command which must be closed first"

I googled and found the solution here 

http://stackoverflow.com/questions/18475195/error-there-is-already-an-open-datareader-associated-with-this-command-which-mu

Regard.

**Comment by Kaushik1987** [comment] 2015-05-04 08:08
This can be easily solved by allowing MARS in your connection string. Add MultipleActiveResultSets=true to the provider part of your connection string. I do not know how it works, but has resolved by error.

**Comment by riverstore** [comment] 2015-05-04 08:13
I also use MultipleActiveResultSets=true and it work, I just want to notice the developers

**Comment by muratcakir** [comment] 2015-05-04 22:42
We had MARS enabled until V1.2, but disabled it due to performance reasons. Anyway, we cannot reproduce the error above.

**Closed** 2015-05-07 17:01 UTC
