### ISSUE TITLE
Themevars.less not found

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#324] opened 2014-08-21 00:51 UTC
I downloaded 2.0 version and it runs fine when, I run it in VS 2013. 
I deployed as per "How To Deploy" guidelines to Local IIS 8.5. 
It throws error that 

<strong>System.IO.FileNotFoundException: File '/.db/themevars.less' not exist.</strong>

I don't such file in "src" or "lib" folder. 

Why I am not getting this error when I run in it VS 2013. Why only it is happening when I host it in IIS?

More information: 

[FileNotFoundException: File '/.db/themevars.less' not exist.] 
BundleTransformer.Less.Translators.LessTranslator.FillDependencies(String rootAssetUrl, LessStylesheet parentStylesheet, DependencyCollection dependencies) +1109

BundleTransformer.Less.Translators.LessTranslator.InnerTranslate(IAsset asset, LessCompiler lessCompiler, Boolean enableNativeMinification) +737

BundleTransformer.Less.Translators.LessTranslator.Translate(IList<code>1 assets) +556

BundleTransformer.Core.Transformers.TransformerBase.Translate(IList</code>1 assets, Boolean isDebugMode) +126

BundleTransformer.Core.Transformers.CssTransformer.Transform(IList<code>1 assets, BundleResponse bundleResponse, VirtualPathProvider virtualPathProvider, HttpContextBase httpContext, Boolean isDebugMode) +113

BundleTransformer.Core.Transformers.TransformerBase.Process(BundleContext context, BundleResponse response, Boolean isDebugMode) +426

System.Web.Optimization.Bundle.ApplyTransforms(BundleContext context, String bundleContent, IEnumerable</code>1 bundleFiles) +272

SmartStore.Web.Framework.Themes.SmartStyleBundle.GenerateBundleResponse(BundleContext context) +210

System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context) +65 
System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath) +253

System.Web.Optimization.AssetManager.EliminateDuplicatesAndResolveUrls(IEnumerable<code>1 refs) +494

System.Web.Optimization.AssetManager.DeterminePathsToRender(IEnumerable</code>1 assets) +928

System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths) +34

SmartStore.Web.Framework.UI.BundleBuilder.Build(BundleType type, IEnumerable<code>1 files) +607

SmartStore.Web.Framework.UI.PageAssetsBuilder.GenerateCssFiles(UrlHelper urlHelper, ResourceLocation location, Nullable</code>1 enableBundling) +795

SmartStore.Web.Framework.UI.LayoutExtensions.SmartCssFiles(HtmlHelper html, UrlHelper urlHelper, ResourceLocation location, Nullable`1 enableBundling) +119

ASP._Page_Views_Shared__Root_Head_cshtml.Execute() in g:\Products\almITeCommerce\Deployment\Views\Shared_Root.Head.cshtml:109

System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +280 
System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +125 

Please help! 
Thanks 
Venky

> Migrated from CodePlex: [Issue #322](https://smartstore.codeplex.com/workitem/322) from [venkigun](https://www.codeplex.com/site/users/view/venkigun), on 4/10/2014 3:29:27 AM

**Comment by donaldmasole** [comment] 2015-07-02 19:26
Hi Guys, im also getting the File '/.db/themevars.less' not exist error when hosting the application in IIS, has anyone found a solution to this problem.

Thanks for the help!

**Comment by Casimodo72** [comment] 2015-09-23 23:24
Hi, I'm getting the same error on Azure: "File '/.db/themevars.less' not exist".

1) I've published the app to Azure
2) Installed the app smoothly
3) but then hit the error when navigating to the site

On the other hand, locally - via IIS Express - the app runs fine.

Using VS 2015 Ent and your feature/export-framework branch as of today.

This is a piece of the event log analysis report from Azure:

![smartstorenet-startup-error-01](https://cloud.githubusercontent.com/assets/10551738/10061487/8bec57f6-6259-11e5-9f67-bf2714f4f3ca.png)

Regards,
Kasimier Buchcik

**Comment by theclai** [comment] 2015-11-24 06:02
Does error already solve ?

**Comment by GonMor** [comment] 2015-11-27 14:27
Same problem to me with version 2.2.2
Please help..

**Comment by GonMor** [comment] 2015-11-30 16:07
Nobody know how solve it? please...

thanks

**Comment by muratcakir** [comment] 2015-11-30 22:20
I'm on it. Trying really hard to reproduce and debug. Not so easy, since it's an environmental issue.

**Comment by cja100** [comment] 2015-11-30 22:31
How did you guys build and deploy? web deploy or using the ClickToBuild.cmd and transferring the build?

**Comment by theclai** [comment] 2015-12-01 04:49
I use web deploy from visual studio 2015

**Comment by GonMor** [comment] 2015-12-01 08:54
Same to me. Publish (web deploy) from source code with visual studio 2015. I have installed locally in windows 10 the IIS from features and same problem but from visual studio 2015 works fine.
Also if I remove from appdata\settings.txt to forcefirst use the compiled code works fine the shop ask me about if I want a new database and later the app configure all, working correclty.
The problem is when I want use present settings.txt to maintain and update present database.
This only works in first use, if you try first with settings.txt later the error continue although you remove settings.txt, something is saved into any place.

I hope that this help you ;-)

thanks

**Comment by cja100** [comment] 2015-12-01 09:04
So I think I had the same issue with web deploy, I don't think smartstore currently supports it, you need to use the clicktobuild.cmd

**Comment by GonMor** [comment] 2015-12-01 10:38
![errorbuild](https://cloud.githubusercontent.com/assets/16048088/11498472/eac05524-981f-11e5-91d7-92de646fc491.JPG)

I received errors with I try use clicktobuild.cmd I have tried two desktops, windows 10 x64 and windows 7 x 64

**Comment by GonMor** [comment] 2015-12-01 10:44
![screenshot - 01_12_2015 11_43_07](https://cloud.githubusercontent.com/assets/16048088/11498634/d3c38214-9820-11e5-866c-8ed86f5f3c28.jpg)

**Comment by GonMor** [comment] 2015-12-01 11:15
I have changed 12.0 by 14.0 into build.bat and run from cmd like administrator and are running now.
I will tell you later if works the new code compiled ;-)

thanks for all

**Comment by GonMor** [comment] 2015-12-01 11:29
I have had the next error...
![screenshot - 01_12_2015 12_16_45](https://cloud.githubusercontent.com/assets/16048088/11499524/f7897608-9826-11e5-8da2-91431b6ba614.jpg)

BUT WORKS!
I need test all shop but at least I don't receive the error "File '/.db/themevars.less' not exist"

Thanks

**Comment by inbanco** [comment] 2016-01-21 05:12
i'm having the same issue where /SmartStoreNET-2.x/src/Presentation/SmartStore.Web/Themes/Alpha/Content/~/.db/themevars.less' wasn't found (404)	

it's breaking the .less process so css isn't working.

it's a new installation and i'm running local dev on win8.1 / iis 8.5 / VS2012

i'm not deploying yet. i'm trying to work with the sln in VS. can someone help me out please?

**Comment by muratcakir** [comment] 2016-01-21 18:15
Min. IDE requirement for SmartStore.NET is **VS 2013**.

**Comment by inbanco** [comment] 2016-01-21 22:48
@muratcakir  thanks for the reply, it explains some of the issues i'm facing. I'll give VS2015 community a go

**Comment by inbanco** [comment] 2016-01-22 03:42
@muratcakir i'm still having .less issues with VS2015. Do i need to have a .less plugin installed? i've attached the error i get when i run
Thanks for you help

![2016-01-22 14_40_06-during translation of less-code readed from the file _themes_soap_content_them](https://cloud.githubusercontent.com/assets/13458999/12501853/3b74c850-c116-11e5-9b39-d7c7807239a5.png)

**Comment by inbanco** [comment] 2016-01-22 04:58
all good - working now - thanks

**Closed** 2016-02-15 17:20 UTC
Labels: bug, cpimp, important, ui

**Comment by xav12** [comment] 2016-07-22 07:47
some one help me, I am new bee and still get the error

File '/.db/themevars.less' not exist.
![capture](https://cloud.githubusercontent.com/assets/20593238/17050072/2aff415a-501b-11e6-8c41-948d095632cc.PNG)
