### ISSUE TITLE
How to build a new plugin - template

### ISSUE THREAD

**Issue by mach37** [smartstoreag/SmartStoreNET#685] opened 2015-05-03 14:43 UTC
Can you please provide some info in English so I can build my own plugin.

I love this over Nop Commerce!!! this is way better, I love the auto-update feature, now lets see if nop tries and copies SmartStore hahahhaaaa

Friendlier licensing

**Comment by mgesing** [comment] 2015-05-04 13:44
I would take a look at an existing [plugin](https://github.com/smartstoreag/SmartStoreNET/tree/2.x/src/Plugins) and find one that best matches my needs. Then I would copy the plugin, change the ProjectGuid of the project file, rename files, names, namespaces and so on and finally I would replace functional code by my own code.

**Comment by net4u** [comment] 2015-08-17 12:39
Maybe more useful a generic empty plugin (and if related to payments minimal dependencies to related model(s) and controllers)

**Comment by mach37** [comment] 2017-01-09 05:37
hey any progress on building plugins and skinning easier?

**Comment by Michael-Herzog** [comment] 2017-09-14 14:47
Duplicate of https://github.com/smartstoreag/SmartStoreNET/issues/822

**Closed by Michael-Herzog** 2017-09-14 14:47 UTC
