### ISSUE TITLE
Identity Membership V2.2 MVC 6

### ISSUE THREAD

**Issue by mach37** [smartstoreag/SmartStoreNET#686] opened 2015-05-03 14:56 UTC
Hello, I am trying to migrate some functionality as plug-ins (I created a ticket for the plug-in architecture).
1.     Can you tell me - how to reuse the _Identity Membership, Roles V2.2_ easily into your platform. I need this functionality to watch which users will be allowed.
2.     Can you provide an easy admin GUI for which controllers/actions are authorized for which roles, using reflection ###### The main issue here is an easy way to manage members, security and roles ######
3.     Are you planning on using MVC 6 since this merges both MVC and web API (if so please share any info in your roadmap)
4.     Are we allowed to use this framework for other things other that a store, and would that breaking your licensing
5.     Do you plan on having US based usergroups or sessions.
6.     Themeing engine, it would be nice to let users create their own themes at least change colors like so... for e.g. http://bit.ly/1KEw4zA  or  http://bit.ly/1IClDxj  - I believe this would go a long way
7.     Can you please make an easy to understand picture of the architecture to follow and read easily. So we can help our selves when we write code. ###### a) how to tie into your framework b) where to tie in c) what should we inherit from d) where to store data e) nuget or bower template for plugin  ######

Also, let me say that this is exceptional work on extending a decent framework and NOP folks should have really encouraged your effort not dissuaded your effort (goes against open source and software sharing community). We're all big fans of yours, we were saddened to see them argue with you. Hopefully your model opens others to take on your framework.

Lastly, you're 100% right on building smartstore, this list might seem long, I only wanted to share feedback/issues that might help the user community adopt your framework easier.

**Comment by muratcakir** [comment] 2015-05-04 22:54
Thank you very much for your kind feedback. It's appreciated.

1. You mean the official ASP.NET Identity Framework? If yes, it's surely not trivial to replace the existing membership system. It's on our roadmap anyway for a future release, so I bet it's better to wait :-)
2. Any scenario describing it's usefulness?
3. Yes, we do. Could take a while though (after it is officially released). It's a tremendous amount of work.
4. No, it would NOT break the license.
5. ???
6. You can do this already, although not WYSIWYG. No top priority for us. Maybe the community can contribute a plugin? ;-)
7. At the moment you're on your own. But a Developer Guide is on it's way. Here again: a lot of work.

**Comment by Michael-Herzog** [comment] 2017-07-20 14:09
Duplicate of: https://github.com/smartstoreag/SmartStoreNET/issues/149

**Closed by Michael-Herzog** 2017-07-20 14:09 UTC
