### ISSUE TITLE
JavaScript error after removing the last item in shopping cart (SmartStore 3.x)

### ISSUE THREAD

**Issue by iherwald** [smartstoreag/SmartStoreNET#1134] opened 2017-05-15 11:18 UTC
A JavaScript error occures after the user removed the last item in the current shopping cart:

_Unhandled exception at line 959, column 35 in http://localhost:61700/cart

0x800a138f - Laufzeitfehler in JavaScript: Die Eigenschaft "hide" eines undefinierten oder Nullverweises kann nicht abgerufen werden._

Environment: Visual Studio 2015, Internet Explorer 11

**Comment by Michael-Herzog** [comment] 2017-05-15 16:37
Hi,

I can't reproduce this error with IE 11. Can you provide a link or a step by step description on how to reproduce this? I'm afraid else I'd have to close this issue as not reproducible. 

Regards

**Comment by Michael-Herzog** [comment] 2017-05-15 16:38
Closed to soon ;-) This was by accident. Sorry!

**Comment by iherwald** [comment] 2017-05-16 05:35
1. Start SmartStore 3.0.0 in Visual Studio 2015 (configuration: debug, IE 11)
2. Sign in
3. Ensure you have an empty shopping cart
4. Add a product to the shopping cart
5. Open shopping cart from the _my-account-dropdown-menu_
6. Remove the (only) product

-> Now, the error will be displayed by Visual Studio.

**Closed** 2017-05-16 09:50 UTC
