### ISSUE TITLE
Colors image

### ISSUE THREAD

**Issue by muratcakir** [smartstoreag/SmartStoreNET#389] opened 2014-08-21 00:53 UTC
A few months agoo I asked if it was possible to show images of colors (not a color number) here

<a href="http://www.bauhaus-classics24.com/charles-eames-lounge-chair#.U328OijG6z4" rel="nofollow">http://www.bauhaus-classics24.com/charles-eames-lounge-chair#.U328OijG6z4</a>

they have done what I wanted can someone explain how to get this done 

Regards, 
Hans

> Migrated from CodePlex: [Issue #387](https://smartstore.codeplex.com/workitem/387) from [Scholten](https://www.codeplex.com/site/users/view/Scholten), on 5/22/2014 9:07:41 AM

**Comment by muratcakir** [comment] 2016-07-11 17:13
Related to #995 and #996

**Comment by Michael-Herzog** [comment] 2017-02-06 15:47
Duplicate of:
https://github.com/smartstoreag/SmartStoreNET/issues/389

**Closed by Michael-Herzog** 2017-02-06 15:47 UTC
Labels: catalog, cpimp, facetednav
