### ISSUE TITLE
Error while creating new category

### ISSUE THREAD

**Issue by AlfVat** [smartstoreag/SmartStoreNET#1493] opened 2018-08-13 15:19 UTC
Hi.
i cloned this solution on my pc and rebuild all projects as suggested in manual.
everything was ok. but in admin panel when i want to add any category i get this error:

> System.Data.SqlClient.SqlException: 'The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Category_dbo.Picture_PictureId". The conflict occurred in database "ss03", table "dbo.Picture", column 'Id'.
> The statement has been terminated.'

in CachingCommand line 169:

`var result = _command.ExecuteReader(behavior);`

and in browser i got this error page:

>  Controller: Category, Action: Create
> 
> An error occurred while updating the entries. See the inner exception for details.
> 
> An error occurred while updating the entries. See the inner exception for details.
> 
> The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Category_dbo.Picture_PictureId". The conflict occurred in database "ss03", table "dbo.Picture", column 'Id'. The statement has been terminated. 

i know this error occurred because i didnt select any picture for this category.

**Comment by mgesing** [comment] 2018-08-13 20:25
Caused by 5883a64ad035e7c5ce3b28649bfe0a50ddb7c006

**Comment by mgesing** [comment] 2018-10-02 18:39
Resolved by 22c6d881ec24bc7cd9aff3466967155ac705d18f.

**Closed by mgesing** 2018-10-02 18:39 UTC
Labels: bug
